# -*- coding: utf-8 -*-
"""Ana_Milena_Rosero_Unigarro_Reto_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ix1h3OZ49pTvPmFMw1EMSm6uPopCdJdy
"""

# o Instalación numpy con referencia np.
!pip install numpy
import numpy as np

#Instalación del paquete del toolbox de redes neuronales tensorflow, versión 2.7.0:
!pip install tensorflow==2.7.0

# Selecciona en la librería matplotlib el método figure
import matplotlib.pyplot as plt

fig = plt.figure()

#muestra todo el stack de librerias del entorno usado
!pip list

!pip install cartopy
import cartopy

# se debe instalar las siguientes librerias para porder ejecutar los comandos
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

# Crea una figura y un conjunto de ejes con la proyección de proyección plana
fig, ax = plt.subplots(subplot_kw={'projection': ccrs.PlateCarree()})

# Dibuja límites de países
ax.add_feature(cfeature.BORDERS, linestyle='-', alpha=0.5)

# Dibuja paralelos y meridianos
ax.gridlines(draw_labels=True, linestyle='--')

# Coordenadas de Bogotá, Colombia
colombia_lat, colombia_lon = 4.6097, -74.0817

# Dibuja un marcador en Colombia
ax.plot(colombia_lon, colombia_lat, 'ro', markersize=6, transform=ccrs.PlateCarree())

# Etiqueta el marcador
ax.text(colombia_lon + 2, colombia_lat + 2, 'Colombia', fontsize=12, transform=ccrs.PlateCarree())

# Muestra el mapa
plt.show()