# -*- coding: utf-8 -*-
"""Reto 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/120vEHgLynIzlTBHVVqCDoNwSpmet4tJC

Punto 1. Aplicación para la gestión de recolección y mantenimiento de los cultivos de una huerta escolar
"""

from ast import While
# Menú principal
print('¿Con qué cultivo cuentan en la huerta escolar?')
nombre_cultivo= input('''
1. Lechuga
2. Berenjena
3. Arroz
''')
# Submenú cultivo 1: Lechuga
# El condicional "while" evalua si la condición (nombre_cultivo es igual a 1) y muestra las opciones del submenú
while int(nombre_cultivo) ==1:
  print('¿Qué dato deseas conocer sobre tu cultivo?')
  posibilidades= input('''
  1. Horarios de riego
  2. Etapas del cultivo
  3. Información contable
  4. Salir
  ''')
  # Impresion opción 1 del submenú: Gestión de cultivo
  # El condicional "if" esta itinerado al "while" y cumple la función de evaluar si la opción seleccionada por el usuario en el submenú es igual a 1 e imprimir la información correspondiente
  if int(posibilidades) ==1:
    print('''
    - Riego:

    Debido a que las lechugas tienen un sistema de raíces poco profundas, son preferibles las sesiones de riego pequeñas pero
    frecuentes. De hecho, lo mejor es mantener el suelo húmedo y regar las plantas temprano en la mañana o al anochecer.

    - Abonado:

    Las actividades de abonado dependen del clima y el estado del cultivo, sin embargo, hay que tener en cuenta que la lechuga
    es una planta exigente en abonado potásico, debiendo cuidar los aportes de este elemento, especialmente en épocas de bajas
    temperaturas; y al consumir más potasio va a absorber más magnesio, por lo que habrá que tenerlo en cuenta a la hora de
    equilibrar esta posible carencia.

    ¡Ojo con el exceso de abono!

    - Mantenimiento:

    Diariamente, preferiblemente temprano en la mañana o al anochecer. Importante saber que este es un cultivo que no acepta
    competencia con las mala hierbas, por lo que habrá que estar pendientes de ellas y retirarlas lo más pronto posible.

    ''')
    # El "continue" permite que el usuario reinicie el ciclo, es decir, retorne al submenú
    continue
    # Impresión opción 2 del submenú: Etapas del cultivo
    # El condicional "elif" quiere decir que el programa evalúa la opción 1 ('if') y si esta no se cumple, continúa con la 2 y en caso de ser verdadera, imprime la información correspondiente
  elif int(posibilidades) ==2:
      print('''
      Las etapas del cultivo de la lechuga son:

      1. Plántula (7-14 días desde la germinación hasta la formación de las primeras hojas)
      2. Crecimiento vegetativo (30-45 días desde la formación de las primeras hojas verdaderas)
      3. Cosecha (60-130 días desde la siembra)
      ''')
      # El "continue" permite que el usuario reinicie el ciclo, es decir, retorne al submenú
      continue
      # Impresión opción 3 del submenú: Información contable
      # Si las opciones 1 y 2 son falsas, el programa evalúa la 3 y si es verdadera imprime la información correspondiente
  elif int(posibilidades) ==3:
    print('Información contable')
    # Pregunta la duración del cultivo
    duracion_cultivo= int(input('Ingresa los meses de duración del cultivo: '))
    total = 0
    menor_que= 100000
    # Información sobre gastos de acuerdo con la duración del cultivo
    print('''
    Gastos
    ''')
    # Solicitud de información al usuario
    # En este caso el "for in range" despliega la lista a diligenciar de acuerdo con los
    for mes in range (1, duracion_cultivo + 1):
      gastos0= float(input(f'Para el mes {mes}, ingrese los gastos relacionados con medicamentos: '))
      gastos1= float(input(f'Para el mes {mes}, ingrese los gastos imprevistos: '))
      gastos_totales= (gastos0 + gastos1)
      total += gastos_totales
      # Suma de todos los gastos mensuales del cultivo
      print('Los gastos totales del cultivo fueron de: ' + str(total))
      # Información sobre los meses en los que no hubo gastos
      if gastos_totales == 0:
        print(f'En el mes {mes} no hubo gastos')
      # Impresión de los menos en los que los gastos fueron menores a 100.000 pesos
      elif gastos_totales <= menor_que:
        print(f'En el mes {mes} los gastos fueron menores de 100.000 pesos')
    # Información sobre los costos de acuerdo con la duración del cultivo
    print('''
    Costos
    ''')
    Total= 0
    costos0_total= []
    # Solicitud de información al usuario
    for mes in range (1, duracion_cultivo + 1):
      costos0= float(input(f'Para el mes {mes}, ingrese el valor de la mano de obra empleada: '))
      costos1= float(input(f'Para el mes {mes}, ingrese el valor del abono: '))
      costos2= float(input(f'Para el mes {mes}, ingrese el valor del agua de riego: '))
      costos3= float(input(f'Para el mes {mes}, ingrese el valor destinado al mantenimiento del cultivo: '))
      # Cálculo de costos totales del cultivo por mes
      costos_totales= (costos0 + costos1 + costos2 + costos3)
      Total += costos_totales
      costos0_total.append(costos0)
      print('Los costos totales del cultivo fueron de: ' + str(Total))
      # Impresión cuando los costos de un mes son mayores que los gastos de ese mes
      if costos_totales >= gastos_totales:
        print(f'En el mes {mes} los costos superaron los gastos')
      elif costos_totales <= gastos_totales:
        print(f'En el mes {mes} los costos fueron menores que los gastos')
    # Total costo mano de obra
    print('Los costos totales de la mano de obra fueron de ' + str(sum(costos0_total)))
    # Promedio de costos fijos y variables
    promedio_cf_cv= Total/total
    print('El promedio de costos fijos y costos variables es de ' + str(promedio_cf_cv))
    # Información sobre la producción
    print('''
    Producción
    ''')
    # Solicitud de información al usuario
    valor_produccion= float(input('Ingrese el valor de la producción en el mercado: '))
    q_produccion= float(input('Ingrese la cantidad producida en el mes: '))
    total_produccion= (valor_produccion * q_produccion)
    # Cálculo de la ganancia
    suma_costos= (Total + total)
    ganancias= (total_produccion - suma_costos)
    # Variables para el cálculo del incremento de 37%
    valor_aumento= 37
    incremento= valor_produccion * (valor_aumento/100)
    valor_con_aumento= (valor_produccion + incremento)
    total_produccion= (valor_con_aumento * q_produccion)
    ganancias= total_produccion - suma_costos
    # Descuento del 5% de los costos totales
    valor_descuento= 5
    descuento= costos_totales *(valor_descuento/100)
    costos_totales_con_descuento= (costos_totales - descuento)
    # Descuento del 63% de la cantidad producida
    valor_descuento= 63
    descuento= q_produccion * (valor_descuento/100)
    q_produccion_total= float(q_produccion - descuento)
    total_produccion= (valor_produccion * q_produccion_total)
    print('Este cultivo obtuvo ingresos por ' + str(total_produccion))
    ganancias=(total_produccion - costos_totales_con_descuento)
    # Impresión cuando el usuario obtuvo ganancias
    if ganancias >= 0:
      print('Y ' + str(ganancias) + ' de ganancias')
    # Impresión cuando el usuario obtuvo pérdidas
    elif ganancias <= 0:
      print('Pero ' + str(ganancias) + ' de pérdidas')
    continue
  # Impresión opción 4 del submenú: Salir
  elif int(posibilidades) ==4:
    print('Fin de la consulta')
    break
# Submenú cultivo 2: Berenjena
while int(nombre_cultivo) ==2:
  print('¿Qué dato deseas conocer sobre tu cultivo?')
  posibilidades1= input('''
  1. Horarios de riego
  2. Etapas del cultivo
  3. Información contable
  4. Salir
  ''')
  # El "if" permite imprimir la información correspondiente con la gestión del cultivo cuando el usuario selecciona la opción 1
  if int(posibilidades1) ==1:
    print('''
    - Riego:

    Las berenjenas generalmente tienen tolerancia media a alta a la sequía y no les gusta el
    suelo muy humedo, por lo que se recomienda regarlas con un litro de agua cada tres días.

    - Abonado:

    El abono de las berenjenas cubrirá todo el período de vida del cultivo, desde antes de la
    siembra hasta el momento en que inicie la formación de los frutos.

    En algunos casos y según la etapa en la que se encuentre la planta serán necesarios abonos
    semanales durante el verano y la primavera.

    - Mantenimiento:

    Esta es una planta que exige riego regular y buen abono, por lo que es necesario estar
    pendiente para retirar las malas hierbas y equilibrar los nutrientes del suelo.
    ''')
    # El "continue" permite reiniciar el ciclo
    continue
  # El "elif" permite imprimir la información correspondiente con la etapa del cultivo cuando el usuario selecciona la opción 2
  elif int(posibilidades1) ==2:
      print('''
      Las etapas del cultivo de la berenjena son:

      1. Pre-siembra/ siembra
      2. Transplante/ germinación
      3. Desarrollo de la hoja
      4. Floración
      5. Cuajado y crecimiento de frutos (25-40 días desde que la flor se abre y poliniza)
      6. Maduración y cosecha (65-80 días después del transplante)
      ''')
      continue
  # El "elif" permite imprimir la información correspondiente la información contable cuando el usuario selecciona la opción 3
  elif int(posibilidades1) ==3:
    print('Información contable')
    # Pregunta la duración del cultivo
    duracion_cultivo= int(input('Ingresa los meses de duración del cultivo: '))
    total = 0
    menor_que= 100000
    # Información sobre gastos de acuerdo con la duración del cultivo
    print('''
    Gastos
    ''')
    # Solicitud de información al usuario
    for mes in range (1, duracion_cultivo + 1):
      gastos0= float(input(f'Para el mes {mes}, ingrese los gastos relacionados con medicamentos: '))
      gastos1= float(input(f'Para el mes {mes}, ingrese los gastos imprevistos: '))
      gastos_totales= (gastos0 + gastos1)
      total += gastos_totales
      # Suma de todos los gastos mensuales del cultivo
      print('Los gastos totales del cultivo fueron de: ' + str(total))
      # Información sobre los meses en los que no hubo gastos
      if gastos_totales == 0:
        print(f'En el mes {mes} no hubo gastos')
      # Impresión de los menos en los que los gastos fueron menores a 100.000 pesos
      elif gastos_totales <= menor_que:
        print(f'En el mes {mes} los gastos fueron menores de 100.000 pesos')
    # Información sobre los costos de acuerdo con la duración del cultivo
    print('''
    Costos
    ''')
    Total= 0
    costos0_total= []
    # Solicitud de información al usuario
    for mes in range (1, duracion_cultivo + 1):
      costos0= float(input(f'Para el mes {mes}, ingrese el valor de la mano de obra empleada: '))
      costos1= float(input(f'Para el mes {mes}, ingrese el valor del abono: '))
      costos2= float(input(f'Para el mes {mes}, ingrese el valor del agua de riego: '))
      costos3= float(input(f'Para el mes {mes}, ingrese el valor destinado al mantenimiento del cultivo: '))
      # Cálculo de costos totales del cultivo por mes
      costos_totales= (costos0 + costos1 + costos2 + costos3)
      Total += costos_totales
      costos0_total.append(costos0)
      print('Los costos totales del cultivo fueron de: ' + str(Total))
      # Impresión cuando los costos de un mes son mayores que los gastos de ese mes
      if costos_totales >= gastos_totales:
        print(f'En el mes {mes} los costos superaron los gastos')
      elif costos_totales <= gastos_totales:
        print(f'En el mes {mes} los costos fueron menores que los gastos')
    # Total costo mano de obra
    print('Los costos totales de la mano de obra fueron de: ' + str(sum(costos0_total)))
    # Promedio de costos fijos y variables
    promedio_cf_cv= Total/total
    print('El promedio de costos fijos y costos variables es de ' + str(promedio_cf_cv))
    # Información sobre la producción
    print('''
    Producción
    ''')
    # Solicitud de información al usuario
    valor_produccion= float(input('Ingrese el valor de la producción en el mercado: '))
    q_produccion= float(input('Ingrese la cantidad producida en el mes: '))
    total_produccion= (valor_produccion * q_produccion)
    # Cálculo de la ganancia
    suma_costos= (Total + total)
    ganancias= (total_produccion - suma_costos)
    # Variables para el cálculo del incremento de 37%
    valor_aumento= 37
    incremento= valor_produccion * (valor_aumento/100)
    valor_con_aumento= (valor_produccion + incremento)
    total_produccion= (valor_con_aumento * q_produccion)
    ganancias= total_produccion - suma_costos
    # Descuento del 5% de los costos totales
    valor_descuento= 5
    descuento= costos_totales *(valor_descuento/100)
    costos_totales_con_descuento= (costos_totales - descuento)
    # Descuento del 63% de la cantidad producida
    valor_descuento= 63
    descuento= q_produccion * (valor_descuento/100)
    q_produccion_total= float(q_produccion - descuento)
    total_produccion= (valor_produccion * q_produccion_total)
    print('Este cultivo obtuvo ingresos por ' + str(total_produccion))
    ganancias=(total_produccion - costos_totales_con_descuento)
    # Impresión cuando el usuario obtuvo ganancias
    if ganancias >= 0:
      print('Y ' + str(ganancias) + ' de ganancias')
    # Impresión cuando el usuario obtuvo pérdidas
    elif ganancias <= 0:
      print('Pero ' + str(ganancias) + ' de pérdidas')
    continue
  elif int(posibilidades1) ==4:
    print('Fin de la consulta')
    break
  # Submenú cultivo 3: Arroz
while int(nombre_cultivo) ==3:
  print('¿Qué dato deseas registrar sobre tu cultivo?')
  posibilidades1= input('''
  1. Horarios de riego
  2. Etapas del cultivo
  3. Información contable
  4. Salir
  ''')
  if int(posibilidades1) ==1:
    cuidado_cultivo_arroz= input('Ingrese los datos relacionados con la gestión de su cultivo')
    print('Los datos de gestión de su cultivo son los siguientes: ' + cuidado_cultivo_arroz)
    continue
  elif int(posibilidades1) ==2:
    etapas_cultivo_arroz= input('Ingrese los datos sobre las etapas de su cultivo')
    print('Los datos acerca de las etapas de su cultivo son los siguientes: ' + etapas_cultivo_arroz)
    continue
  elif int(posibilidades1) ==3:
    print('Información contable')
    # Pregunta la duración del cultivo
    duracion_cultivo= int(input('Ingresa los meses de duración del cultivo: '))
    total = 0
    menor_que= 100000
    # Información sobre gastos de acuerdo con la duración del cultivo
    print('''
    Gastos
    ''')
    # Solicitud de información al usuario
    for mes in range (1, duracion_cultivo + 1):
      gastos0= float(input(f'Para el mes {mes}, ingrese los gastos relacionados con medicamentos: '))
      gastos1= float(input(f'Para el mes {mes}, ingrese los gastos imprevistos: '))
      gastos_totales= (gastos0 + gastos1)
      total += gastos_totales
      # Suma de todos los gastos mensuales del cultivo
      print('Los gastos totales del cultivo fueron de: ' + str(total))
      # Información sobre los meses en los que no hubo gastos
      if gastos_totales == 0:
        print(f'En el mes {mes} no hubo gastos')
      # Impresión de los menos en los que los gastos fueron menores a 100.000 pesos
      elif gastos_totales <= menor_que:
        print(f'En el mes {mes} los gastos fueron menores de 100.000 pesos')
    # Información sobre los costos de acuerdo con la duración del cultivo
    print('''
    Costos
    ''')
    Total= 0
    costos0_total= []
    # Solicitud de información al usuario
    for mes in range (1, duracion_cultivo + 1):
      costos0= float(input(f'Para el mes {mes}, ingrese el valor de la mano de obra empleada: '))
      costos1= float(input(f'Para el mes {mes}, ingrese el valor del abono: '))
      costos2= float(input(f'Para el mes {mes}, ingrese el valor del agua de riego: '))
      costos3= float(input(f'Para el mes {mes}, ingrese el valor destinado al mantenimiento del cultivo: '))
      # Cálculo de costos totales del cultivo por mes
      costos_totales= (costos0 + costos1 + costos2 + costos3)
      Total += costos_totales
      costos0_total.append(costos0)
      print('Los costos totales del cultivo fueron de: ' + str(Total))
      # Impresión cuando los costos de un mes son mayores que los gastos de ese mes
      if costos_totales >= gastos_totales:
        print(f'En el mes {mes} los costos superaron los gastos')
      elif costos_totales <= gastos_totales:
        print(f'En el mes {mes} los costos fueron menores que los gastos')
    # Total costo mano de obra
    print('Los costos totales de la mano de obra fueron de: ' + str(sum(costos0_total)))
    # Promedio de costos fijos y variables
    promedio_cf_cv= Total/total
    print('El promedio de costos fijos y costos variables es de ' + str(promedio_cf_cv))
    # Información sobre la producción
    print('''
    Producción
    ''')
    # Solicitud de información al usuario
    # El usuario va a ingresar datos en arrobas, entonces hay que convertirlos a kilos. Fórmula: @ * 11.339= kg.
    q_produccion= float(input('Ingrese la cantidad de arrobas recolectadas en el mes: '))
    conversion= (q_produccion * 11.339)
    print('Su producción actual en kilos corresponde a ' + str(conversion))
    # El usuario va a ingresar datos sobre el precio de la arroba, hay que convertilos a kilos
    valor_produccion= float(input('Ingrese el valor de la arroba en el mercado: '))
    valor_en_kilos= (valor_produccion * conversion)
    print('El valor de las arrobas producidas en kilos es de ' + str(valor_en_kilos))
    total_produccion= (conversion * valor_en_kilos)
    print('Este cultivo obtuvo ingresos por ' + str(total_produccion))
    # Cálculo de la ganancia con unidad kilos
    suma_costos= (Total + total)
    ganancias= (total_produccion - suma_costos)
    # Impresión cuando el usuario obtuvo ganancias
    if ganancias >= 0:
      print('Y ' + str(ganancias) + ' de ganancias')
    # Impresión cuando el usuario obtuvo pérdidas
    elif ganancias <= 0:
      print('Pero ' + str(ganancias) + ' de pérdidas')
    # Variables para el cálculo del incremento de 37%
    incremento= 0.37
    valor_unidad_kg= (valor_en_kilos/conversion)
    valor_con_aumento= (valor_unidad_kg + incremento)
    total_produccion= (valor_con_aumento * conversion)
    ganancias_con_aumento= total_produccion - suma_costos
    diferencia_ganancias= (ganancias_con_aumento - ganancias)
    print('Si el valor del kilo de arroz aumenta 37%, las ganancias serían de ' + str(diferencia_ganancias))
    # Descuento del 5% de los costos totales
    descuento= 0.05
    costos_totales_con_descuento= (costos_totales - descuento)
    # Descuento del 63% de la cantidad producida en unidad arrobas
    descuento= 0.63
    q_produccion_descuento= (q_produccion - descuento)
    total_produccion= (valor_produccion * q_produccion_descuento)
    ganancias=(total_produccion - costos_totales_con_descuento)
    if costos_totales_con_descuento and total_produccion:
      print('Si los costos se reducen en 5% y la cantidad de arrobas producidas en 63%, la ganancia sería de ' + str(ganancias))
    continue
  elif int(posibilidades1) ==4:
    print('Fin de la consulta')
    break