# -*- coding: utf-8 -*-
"""Reto3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/111FsrRSHuQzjD0X5fPLhYcrl5tmd-UE7
"""

# Definir un menú principal, el usuario puede seleccionar una opción ingresando el número correspondiente.
def menuP():
  print("\nMENU MENU PRINCIPAL: \n 1. DATOS DEL CULTIVO  \n 2. HORARIO DE GESTIÓN DE CULTIVO \n 3. ETAPAS DEL CULTIVO  \n 4. INFORMACIÓN CONTABLE  \n 5. SALIR")
def menuEC():
 print("\nETAPAS DEL CULTIVO  \n 1. SIEMBRA  \n 2. CRECIMIENTO  \n 3. COSECHA")
def menuIC():
  print("\nINFORMACIÓN CONTABLE: \n 1. COSTOS FIJOS: \n 2. PRODUCCION  \n 3. INFORME FINAL")
def SubIC():
  print("\nSUB MENU COSTOS FIJOS: \n 1. MANO DE OBRA: \n 2. AGUA \n 3. MANTENIMIENTO \n 4. ABONO \n 5. IR ATRÁS")
def SubProd():
 print("\nSUB MENU PRODUCCION \n 1. VALOR DEL MERCADO: \n 2. CANTIDAD RECOGIDA  \n 3. IR ATRÁS ")

Mano_de_obra = 0
Agua = 0
Mantenimiento = 0
Abono = 0
Valor_Producto = 0
Cantidad_Recogida = 0
etapa_de_cultivo = ""
nom =""
HoraMan =""
HoraReg =""
HoraAbo =""

print("APLICACIÓN PARA LA GESTIÓN DE RECOLECCIÓN Y MANTENIMIENTO DE LOS CULTIVOS DE LA HUERTA ESCOLAR .")
while True:
 menuP()
 op= input('Ingrese una opcion del Menu Principal :')

# Si el usuario elige "Datos del Cultivo," se le pide ingresar el nombre del cultivo.
 if op == "1":
   print("Datos del Cultivo")
   nom = input('Nombre del Cultivo: ')

#Si el usuario elige "Horario de Gestión de Cultivo," el programa verifica si se ha ingresado información sobre el horario de mantenimiento, riego y abono para el cultivo seleccionado
 elif op == "2":
   if HoraMan =="" and HoraReg =="" and HoraAbo =="":
    print("\nDebe elegir una Etapa de Cultivo para visualizar el Informe de Gestión de Cultivo")
   else:
    print("\nInforme de Gestión de Cultivo para " + etapa_de_cultivo
          +"\n 1. Horario de Mantenimiento " + HoraMan
          + "\n 2. Horario de Regado " + HoraReg
          + "\n 3. Horario de Abono " + HoraAbo
          + "\n Varian los horarios para cada ETAPA del Cultivo ")

# Si el usuario elige "Etapas del Cultivo," se muestra un submenú con las etapas disponibles (siembra, crecimiento y cosecha). El usuario puede seleccionar una etapa y luego ingresar los horarios correspondientes.
 elif op == "3":
    menuEC()
    opEC = input('Digite la opcion que desea del Menu ETAPAS DEL CULTIVO  :' )

    if opEC == "1":
      etapa_de_cultivo = "Siembra"
      HoraMan = input('Ingrese el dia y hora de Mantenimiento: ')
      HoraReg = input('Ingrese el dia y hora de Regado: ')
      HoraAbo = input('Ingrese el dia y hora de Abono: ')
    elif opEC == "2":
      etapa_de_cultivo = "Crecimiento"
      HoraMan = input('Ingrese el dia y hora de Mantenimiento: ')
      HoraReg = input('Ingrese el dia y hora de Regado: ')
      HoraAbo = input('Ingrese el dia y hora de Abono: ')
    elif opEC == "3":
      etapa_de_cultivo = "Cosecha"
      HoraMan = input('Ingrese el dia y hora de Mantenimiento: ')
      HoraReg = input('Ingrese el dia y hora de Regado: ')
      HoraAbo = input('Ingrese el dia y hora de Abono: ')

    else:
      print("Opción Incorrecta")

# Si el usuario elige "Información Contable," se muestra otro submenú con opciones relacionadas con costos fijos y producción. El usuario puede ingresar valores para costos fijos (mano de obra, agua, mantenimiento y abono) y datos de producción (valor del mercado y cantidad recogida).
 elif op == "4":
      while True:
        menuIC()
        opcIC = input('Digite la opcion que desea del Menu INFORMACIÓN CONTABLE:' )
        if opcIC == "1":
          while True:
            SubIC()
            opcSubIC = input('Digite la opcion que desea del SUB MENU COSTOS FIJOS:' )
            if opcSubIC == "1":
                Mano_de_obra = float(input("Ingrese el valor de Mano de Obra: "))
            elif opcSubIC == "2":
                Abono = float(input("Ingrese el valor del Agua: "))
            elif opcSubIC == "3":
                Agua = float(input("Ingrese el valor del Mantenimiento: "))
            elif opcSubIC == "4":
                Mantenimiento = float(input("Ingrese el valor del Abono: "))
            elif opcSubIC == "5":
                break
            else:
                print("\nOpción Incorrecta")
                break

        elif opcIC == "2":
          while True:
            SubProd()
            opPro = input('\n Digite la opcion que desea del SUB MENU PRODUCCION :' )
            if opPro == "1":
                Valor_Producto = float(input("Ingrese el valor del Mercado: "))
            elif opPro == "2":
                Cantidad_Recogida = float(input("Ingrese el valor de la Cantidad Recogida: "))
            elif opPro == "3":
                break
            else:
              print("Opción Incorrecta")
              break

        elif opcIC == "3":
            TotalCostos = Mano_de_obra + Agua + Mantenimiento + Abono
            Ganancias = Cantidad_Recogida - TotalCostos
            Aumento = Valor_Producto * 0.37 + Cantidad_Recogida  - TotalCostos
            Disminuye = TotalCostos - 0.5 + Cantidad_Recogida - 0.63
            print("\n\nINFORME FINAL")
            print("Nombre del Cultivo:  ", nom
                + "\n Etapa del Cultivo:  " , etapa_de_cultivo
                + "\n Horario de Mantenimiento:  " , HoraMan
                + "\n Horario de Regado:  " , HoraReg
                + "\n Horario de Abono:  " , HoraAbo
                + "\n Valor promedio de costos Fijos:  " , TotalCostos )

            if Ganancias > 0:
              print("\nLas ganacias Fueron de : ", Ganancias)
              print("Si aumentamos 37% al Valor Producto las ganancias obtenidas serian de:  ", Aumento)
              print("Si los costos y gastos se disminuyen en un 5% y la cantidad de arrobas producidas en un 63%  las ganancias serian de:  ", Disminuye)
            else:
              print("No hubieron Ganancias el cultivo esta en Perdidas")
            break

 elif op=="5":
    print("\nFin del Programa")
    break

 else: print("\nOpción Incorrecta")