# -*- coding: utf-8 -*-
"""reto3.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1owPA0qXDLLMCfii4pF9Vnki0f22Hl7zL
"""

print("Bienvenidos a Nuestra Huerta Escolar")
# Función para mostrar el menú principal
def mostrar_menu_principal():
    print("  ")
    print("Opciones del menú principal:")
    print("1. Seleccion del cultivo")
    print("2. Horario de gestión del cultivo")
    print("3. Etapas del cultivo e intervalos")
    print("4. Información contable")
    print("5. Salir")

# Función para mostrar el submenú del tipo cultivo
def mostrar_submenu_cultivo():
    print("Seleccione al cultivo:")
    print("Cultivo 1")
    print("Cultivo 2")
    print("Cultivo 3")
    cultivo = input("1.1 Ingrese cultivo: ")
    print("Días y Horario de Mantenimiento del arroz son: lunes y jueves 4:00 pm")
    print("Días y Horario de regado del arroz son los dias martes y sábados 4:00 pm")
    print("Días y Horario de abono del arroz es el dia viernes 10:00 am")

# Función para mostrar el submenú de gestión del cultivo
def mostrar_submenu_gestion_cultivo():
    print("Horario de gestión del cultivo:")
    cultivo = input("2.1 Ingrese el nombre del cultivo: ")
    print("Días y Horario de Mantenimiento del arroz son: lunes y jueves 4:00 pm")
    print("Días y Horario de regado del arroz son los dias martes y sábados 4:00 pm")
    print("Días y Horario de abono del arroz es el dia viernes 10:00 am")

# Función para mostrar el submenú de etapas del cultivo
def mostrar_submenu_etapas_cultivo():
    print("el cultivo, {cultivo}")
    print("3.1.1 Fase siembra – 30 días – 1 mes")
    print("3.1.2 Fase vegetativa – 90 días – 3 meses")
    print("3.1.3 Fase de cosecha – 30 días – 1 mes")
    print("3.1.4 Total etapas 150 días – 5 meses")

# Función para mostrar el submenú de información contable
def mostrar_submenu_informacion_contable():
    medicamentos = float(input("4.1.1 Ingrese el valor de los medicamentos al mes: "))
    imprevistos = float(input("4.1.2 Ingrese el valor de los imprevistos al mes: "))
    costos_variables = medicamentos + imprevistos
    print(f"4.1.3 Total costos variables: {costos_variables}")

    mano_obra = float(input("4.2.1 Ingrese el valor de la mano de obra al mes: "))
    abono = float(input("4.2.2 Ingrese el valor del abono al mes: "))
    agua = float(input("4.2.3 Ingrese el valor del agua al mes: "))
    mantenimiento = float(input("4.2.4 Ingrese el valor del mantenimiento al mes: "))
    costos_fijos = mano_obra + abono + agua + mantenimiento
    print(f"4.2.5 Total costos fijos: {costos_fijos}")

    arroba = float(input("4.3.1 Ingrese el valor de la arroba: "))
    kilos = float(input("4.3.2 Ingrese la cantidad de kilos recolectados: "))
    produccion = (kilos * arroba) * 12.5
    print(f"4.3.3 Producción: {produccion}")
    print(f"4.3.4 Su producción es: {produccion}")

    print("4.4 Informe económico:")
    print(f"4.4.1 Costos totales por mes: {costos_variables + costos_fijos}")
    print(f"4.4.2 Costos totales mano de obra: {mano_obra * 5}")
    if costos_variables == 0:
        print("4.4.3 Meses sin gastos: No hubo gastos")
    else:
        print("4.4.3 Meses sin gastos: Hubo gastos")
    if costos_variables > 100000:
        print("4.4.4 Gastos mayores a cien mil pesos")
    print(f"4.4.5 Valor promedio de costos fijos y de costos variables: {(costos_fijos + costos_variables) / 2}")
    ganancia = produccion -(costos_fijos + costos_variables)
    if ganancia > 0:
        print(f"4.4.6 Hubo ganancia, muy bien. Ganancia: {ganancia}")
    else:
        print("4.4.6 No hubo ganancia, lo sentimos")

    print("4.4.7 Incremento de 37% del precio de kilo:")
    ganancia_incrementada = ganancia * 1.37
    print(f"El precio de kilo incrementó en 37%, por lo tanto su ganancia es: {ganancia_incrementada}")

# Función principal
def main():
    while True:
        mostrar_menu_principal()
        opcion = input("Seleccione una opción (1/2/3/4/5): ")
        if opcion == '1':
            mostrar_submenu_cultivo()
        elif opcion == '2':
            mostrar_submenu_gestion_cultivo()
        elif opcion == '3':
            mostrar_submenu_etapas_cultivo()
        elif opcion == '4':
            mostrar_submenu_informacion_contable()
        elif opcion == '5':
            print("Gracias por visitar nuestra Huerta Estudiantil")
            break
        else:
            print("Opción no válida. Intente de nuevo.")
if __name__ == "__main__":
    main()