# -*- coding: utf-8 -*-
"""Reto3 Map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153PXXxpx_z4iN1OSTSMr1Xx_gbKyUla1
"""

# ------------ Reto 3: Gestión de Cultivo escolar ------------------

# Datos cultivos: Se enumeran cuatro cultivos, se organizan los datos en listas para facilitar el proceso.

name = ["Arveja","Arroz","Tomate","Espinaca"]
mantener = ["Lunes-Miércoles 9:00 a.m.","Martes 4:00 p.m.","Martes-Viernes 8:00 a.m.","Jueves 10:00 a.m."]
regar = ["Viernes 5:00 p.m.","Lunes-Jueves 8:00 a.m.","Miércoles-Viernes 8:00 a.m.","Martes-Jueves 5:00 p.m."]
abonar = ["Lunes 9:00 a.m.","Martes 8:00 a.m.","Miércoles 5:00 p.m.","Jueves 8:00 a.m."]
etapa_arveja = ["Germinación: 10 días","Floración: 60 días","Cosecha: 130 días"]
etapa_arroz = ["Germinación: 8 días","Desarrollo Vegetativo: 90 días","Cosecha: 150 días"]
etapa_tomate = ["Germinación: 15 días","Desarrollo Vegetativo: 40 días","Cosecha: 81 días"]
etapa_espina = ["Germinación: 5 días","Desarrollo Vegetativo: 38 días","Cosecha: 55 días"]

# Información Contable

# Gastos o costos variables: Se utilizan listas vacías para almacenar la información introducida por el usuario.
medicamentos = []
imprevistos = []

# Costos fijos: Se utilizan listas vacías para almacenar la información introducida por el usuario.
mano_obra = []
abono = []
agua = []
mantenimiento = []

# Producción: Se utiliza una lista vacía para almacenar un solo dato del usuario, el otro dato fue sacado de consulta en google.
produccion = []
precio_arroba = 52500

# Menú principal: Despliega un menú donde el usuario elige una opción.

menuprinc = int(input("Menú \n 1- Horarios de gestión de cultivo \n 2- Etapas de cultivo \n 3- Información contable \n 4- Salir \n"))

# Programa

while menuprinc != 4:

  if menuprinc == 1:
    print("""
    Arveja
    Arroz
    Tomate
    Espinaca""")
    respuesta = input("Digita el nombre del cultivo: ")
    posicion = name.index(respuesta)
    print("El cultivo", name[posicion]," debe ser mantenido: ",mantener[posicion],", debe ser regado",regar[posicion], "debe ser abonado: ",abonar[posicion])

  elif menuprinc == 2:
    print("""
    Arveja
    Arroz
    Tomate
    Espinaca""")
    respuesta = input("Digita el nombre del cultivo: ")
    if respuesta == "Arveja":
      print("El cultivo", respuesta," tiene las etapas: ", etapa_arveja)
    elif respuesta == "Arroz":
      print("El cultivo", respuesta," tiene las etapas: ", etapa_arroz)
    elif respuesta == "Tomate":
      print("El cultivo", respuesta," tiene las etapas: ", etapa_tomate)
    elif respuesta == "Espinaca":
      print("El cultivo", respuesta," tiene las etapas: ", etapa_espina)
    else:
      break

  elif menuprinc == 3:
    print("Ingresa los datos($) contables por mes:")

    print("   |Mes 1|   |Mes 2|   |Mes 3|   |Mes 4|   |Mes 5 ")
    medicamentos = list(map(int, input("Ingrese el valor de los medicamentos para cada mes: $").split()))
    print("   |Mes 1|   |Mes 2|   |Mes 3|   |Mes 4|   |Mes 5 ")
    imprevistos = list(map(int, input("Ingrese el valor de los imprevistos para cada mes: $").split()))
    print("   |Mes 1|   |Mes 2|   |Mes 3|   |Mes 4|   |Mes 5 ")
    mano_obra = list(map(int, input("Ingrese el valor de la mano de obra para cada  mes: $").split()))
    print("   |Mes 1|   |Mes 2|   |Mes 3|   |Mes 4|   |Mes 5 ")
    abono = list(map(int, input("Ingrese el valor del abono para cada  mes: $").split()))
    print("   |Mes 1|   |Mes 2|   |Mes 3|   |Mes 4|   |Mes 5 ")
    agua = list(map(int, input("Ingrese el valor del agua para cada  mes: $").split()))
    print("   |Mes 1|   |Mes 2|   |Mes 3|   |Mes 4|   |Mes 5 ")
    mantenimiento = list(map(int, input("Ingrese el valor del mantenimiento para cada  mes: $").split()))
    print("   |Mes 1|   |Mes 2|   |Mes 3|   |Mes 4|   |Mes 5 ")
    produccion = list(map(int, input("Cantidad de kilos de arroz recolectados: ").split()))

    # a.	Costos totales del cultivo por mes
    print("Costos Totales\n Mes 1 | Mes 2 | Mes 3 | Mes 4 | Mes 5 |")
    costoT=0
    for i in range(len(medicamentos)):
      costoT+=medicamentos[i]+imprevistos[i]+mano_obra[i]+abono[i]+agua[i]+mantenimiento[i]
      print("$",costoT,end=' ')

    # b.	Costos totales de mano de obra
    suma_mano_obra = sum(mano_obra)
    print("\nEl costo total de la mano de obra fue de $",suma_mano_obra)

    # c.	Meses en los cuales no hubo gastos
    gastos=[]
    for i in range(len(medicamentos)):
      gastos.append(medicamentos[i]+imprevistos[i])
    encontrados = 1
    for i in range(len(gastos)):
        if gastos[i] == 0:
            print("No hubo gastos en el mes: {}".format(i+1))
            encontrados += 1

    # d.	Meses en los cuales el gasto fue menor a 100.000
    encontrados = 1
    for i in range(len(gastos)):
        if gastos[i] < 100000:
            print("Hubo gastos menores a $100.000 en el mes: {}".format(i+1))
            encontrados += 1

    # e.	Meses en los cuales el costo total del mes fue mayor al gasto total del mes. ----Esto no tiene sentido----
    print("Dado que el costo total es la suma del gasto total y los costos fijos, todos los meses el costo total será mayor al gasto total mensual")

    # f. Muestre el valor promedio de costos Fijos y costos variables.
    prom_cost_var= (sum(medicamentos)/len(medicamentos))+(sum(imprevistos)/len(imprevistos))
    prom_cost_fij= (sum(mano_obra)/len(mano_obra))+(sum(abono)/len(abono))+(sum(agua)/len(agua))+(sum(mantenimiento)/len(mantenimiento))
    print("El valor promedio de los costos fijos fue: ",prom_cost_fij," y el promedio de costos variables fue: ",prom_cost_var)

    # g.	¿Hubo ganancia?  SI o NO.  Si hubo ¿cuánto dinero fue la ganancia? (dinero que queda después de sacar los costos totales y gastos totales del dinero recibido por la venta de la cosecha)
    venta = (precio_arroba/12.5)*sum(produccion)
    ganancia = venta-sum(medicamentos)-sum(imprevistos)-sum(mano_obra)-sum(abono)-sum(agua)-sum(mantenimiento)
    if ganancia > 0:
      print("Sí hubo ganancia; un total de $",ganancia)
    else:
      print("No hubo ganancia, la pérdida fue de $",ganancia)

    # h.	Si el precio del kilo de arroz se incrementa en un 37% de su valor actual.  ¿Cuál sería la ganancia obtenida?
    nuevo_prec=(precio_arroba/12.5)*1.37
    venta1 = nuevo_prec*sum(produccion)
    ganancia1 = venta1-sum(medicamentos)-sum(imprevistos)-sum(mano_obra)-sum(abono)-sum(agua)-sum(mantenimiento)
    print("Con un aumento del 37% del valor del kilo de arroz la nueva ganancia es $",ganancia1)

    # i.	Si los costos y gastos se disminuyen en un 5% y la cantidad de arrobas producidas en un 63%, ¿cuál seria  la ganancia?
    costoT2=sum(medicamentos)*-1.05+sum(imprevistos)*-1.05+sum(mano_obra)*-1.05+sum(abono)*-1.05+sum(agua)*-1.05+sum(mantenimiento)*-1.05
    produccion1=(sum(produccion)/12.5)*-1.63
    ganancia2=(produccion1*precio_arroba)-costoT2
    print("Con reducción de un 5% en costos y gastos y un 63% de arrobas producidas, la ganancia sería de $",ganancia2)


  else:
    print("Por favor elije una opción válida")

  menuprinc = int(input("Menú \n 1- Horarios de gestión de cultivo \n 2- Etapas de cultivo \n 3- Información contable \n 4- Salir \n"))
  if menuprinc == 4:
    respuesta = (" Gracias por utilizar nuestro aplicativo ")
    print(respuesta)