# -*- coding: utf-8 -*-
"""DeissyCancino,BaironGomez_Reto4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7He9lQtkE1R4G2H72U4w_bd1qRgIhBO
"""

#Deissy Cancino Joya
#Cc 1098730569
#Correo: deissycancino@gmail.com

#Bairon Emir Gomez Peñuela
#Cc 1007961775
#Correo: znoriab@gmail.com


#OPERACIONES BÁSICAS Y ARITMÉTICAS EXTENDIDAS
def suma(n1, n2):
    return n1 + n2

def resta(n1, n2):
    return n1 - n2

def multiplicacion(n1, n2):
    return n1 * n2

def division(n1, n2):
    if n2 == 0:
        return "No se puede divir por 0"
    return n1 / n2

def division_entera(n1, n2):
    if n2 == 0:
        return "No se puede divir por 0"
    return n1 // n2

def residuo(n1, n2):
    if n2 == 0:
        return "No se puede divir por 0"
    return n1 % n2

def potencia(n1, n):
    return n1 ** n

def raiz_n(n1, n):
    if n == 0:
        return "No se puede dividir por 0"
    return n1 ** (1/n)


def valor_absoluto(n1):
   return abs(n1)


def inverso(n1):
    if n1 == 0:
        return "No se puede dividir por 0"
    return 1 / n1

def factorial(n1):
    if n1 < 0:
        return "No se puede realizar el factorial de un número negativo"
    elif n1 == 0:
        return 1
    else:
        return n1 * factorial(n1 - 1)

#OPERACIONES TRIGONOMÉTRICAS

def seno(angulo_grados):
    # Convertir el ángulo de grados a radianes
    angulo_rad = angulo_grados * (3.14159265358979323846 / 180.0)
    # Calcular el seno utilizando la serie de Taylor
    seno_aprox = angulo_rad
    for n in range(1, 10):
        termino = ((-1) ** n) * (angulo_rad ** (2 * n + 1)) / factorial(2 * n + 1)
        seno_aprox += termino
    return seno_aprox

def coseno(angulo_grados):
    # Convertir el ángulo de grados a radianes
    angulo_rad = angulo_grados * (3.14159265358979323846 / 180.0)
    # Calcular el coseno utilizando la serie de Taylor
    coseno_aprox = 1  # El primer término de la serie es siempre 1
    for n in range(1, 10):
        termino = ((-1) ** n) * (angulo_rad ** (2 * n)) / factorial(2 * n)
        coseno_aprox += termino
    return coseno_aprox

def tangente(angulo_grados):
    # Convertir el ángulo de grados a radianes
    angulo_rad = angulo_grados * (3.14159265358979323846 / 180.0)
    # Calcular la tangente utilizando el seno y el coseno
    seno_valor = seno(angulo_grados)
    coseno_valor = ((1 - seno_valor**2)**0.5)
    if coseno_valor != 0:
        tangente_aprox = seno_valor / coseno_valor
        return tangente_aprox
    else:
        return "Tangente indefinida (coseno igual a cero)"

#OPERACIONES ESTADÍSTICAS

def promedio(datos):
    return sum(datos) / len(datos)


def mediana(datos):
    datos.sort()
    n = len(datos)
    if n % 2 == 0:
      mediana = (datos[n // 2 - 1] + datos[n // 2]) / 2
    else:
      mediana = datos[n // 2]
    return mediana

def moda(datos):
    conteo = {}
    for dato in datos:
      if dato in conteo:
        conteo[dato] += 1
      else:
        conteo[dato] = 1
    moda = [key for key, value in conteo.items() if value == max(conteo.values())]
    if len(moda) == len(datos):
      print("No hay una moda clara en los datos.")
    else:
      print(f"La moda es: {', '.join(map(str, moda))}")



def menu_principal():
    while True:
        print("")
        print("Menú Principal")
        print("1. Operaciones Aritméticas")
        print("2. Operaciones Trigonométricas")
        print("3. Operaciones Estadísticas")
        print("4. Salir")

        opcion_principal = input("Seleccione una opción (1/2/3/4): ")

        if opcion_principal == "1":
            menu_aritmetico()
        elif opcion_principal == "2":
            menu_trigonometrico()
        elif opcion_principal == "3":
            menu_estadistico()
        elif opcion_principal == "4":
            print("¡Hasta luego! Gracias por tu tiempo")
            break
        else:
            print("Opción no válida. Seleccione 1, 2, 3 o 4.")

def menu_aritmetico():
    while True:
        print("")
        print("Menú de Operaciones Aritméticas")
        print("1. Suma")
        print("2. Resta")
        print("3. Multiplicación")
        print("4. División")
        print("5. División entera")
        print("6. Residuo")
        print("7. Potencia")
        print("8. Raiz")
        print("9. Valor absoluto")
        print("10. Inverso")
        print("11. Factorial")
        print("12. Volver al Menú Principal")

        opcion_aritmetica = input("Seleccione una opción: ")

        if opcion_aritmetica in ["1", "2", "3", "4", "5", "6"]: #Para no preguntar varias veces los números, lo hacemos evaluar con un "in" para preguntar en esas opciones
          num1 = float(input("Ingrese el primer número: "))
          num2 = float(input("Ingrese el segundo número: "))
        if opcion_aritmetica in ["9", "10", "11"]:
            num1 = float(input("Ingrese el número: "))
        if opcion_aritmetica == "1":
            resultado = suma(num1,num2)
            print(f"El resultado de la suma es: {resultado}")
        elif opcion_aritmetica == "2":
            resultado = resta(num1,num2)
            print(f"El resultado de la resta es: {resultado}")
        elif opcion_aritmetica == "3":
            resultado = multiplicacion(num1,num2)
            print(f"El resultado de la multiplicación es: {resultado}")
        elif opcion_aritmetica == "4":
            resultado = division(num1,num2)
            print(f"El resultado de la división es: {resultado}")
        elif opcion_aritmetica == "5":
            resultado = division_entera(num1,num2)
            print(f"El resultado de la división entera es: {resultado}")
        elif opcion_aritmetica == "6":
            resultado = residuo(num1,num2)
            print(f"El residuo de la operación es: {resultado}")
        elif opcion_aritmetica == "7":
            num1 = float(input("Ingrese la base: "))
            num2 = float(input("Ingrese el exponente: "))
            resultado = potencia(num1,num2)
            print(f"La potencia {num2} de {num1} es: {resultado}")
        elif opcion_aritmetica == "8":
            num1 = float(input("Ingrese el radicando: "))
            num2 = float(input("Ingrese el indice de la raíz: "))
            resultado = raiz_n(num1,num2)
            print(f"La raíz {num2} de {num1} es: {resultado}")
        elif opcion_aritmetica == "9":
            resultado = valor_absoluto(num1)
            print(f"El valor absoluto de {num1} es {resultado}")
        elif opcion_aritmetica == "10":
            resultado = inverso(num1)
            print(f"El residuo de la operación es: {resultado}")
        elif opcion_aritmetica == "11":
            resultado = factorial(num1)
            print(f"El residuo de la operación es: {resultado}")
        elif opcion_aritmetica == "12":
            break
        else:
            print("Opción no válida.")

def menu_trigonometrico():
    while True:
        print("")
        print("Menú de Operaciones Trigonométricas")
        print("1. Seno")
        print("2. Coseno")
        print("3. Tangente")
        print("4. Volver al Menú Principal")

        opcion_trigonometrica = input("Seleccione una opción (1/2/3/4): ")

        if opcion_trigonometrica in ["1", "2", "3"]:
            angulo = float(input("Ingrese el ángulo en grados: "))
        if opcion_trigonometrica == "1":
            resultado = seno(angulo)
            print(f"El seno de {angulo} grados es {resultado}")
        elif opcion_trigonometrica == "2":
            resultado = coseno(angulo)
            print(f"El coseno de {angulo} grados es {resultado}")
        elif opcion_trigonometrica == "3":
            resultado = tangente(angulo)
            print(f"La tangente de {angulo} grados es {resultado}")
        elif opcion_trigonometrica == "4":
            break
        else:
            print("Opción no válida. Seleccione 1, 2, 3 o 4.")


def menu_estadistico():
    while True:
        print("")
        print("Menú de Operaciones Estadísticas")
        print("1. Promedio")
        print("2. Mediana")
        print("3. Moda")
        print("4. Volver al Menú Principal")

        opcion_estadistica = input("Seleccione una opción (1/2/3/4/5): ")

        if opcion_estadistica in ["1", "2", "3"]:
            datos = input("Ingrese una lista de números separados por espacios: ").split()
            datos = [float(d) for d in datos]

        if opcion_estadistica == "1":
           resultado = promedio(datos)
           print(f"El promedio es: {resultado}")
        elif opcion_estadistica == "2":
            resultado = mediana(datos)
            print(f"La mediana es: {resultado}")
        elif opcion_estadistica == "3":
            return moda(datos)
        elif opcion_estadistica == "4":
            break
        else:
            print("Opción no válida. Seleccione 1, 2, 3, o 4.")

if __name__ == "__main__":
    menu_principal()