# -*- coding: utf-8 -*-
"""Reto 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q6Xjgb7G-NgC0ArC18iGlhj0hNyvjKaS

Punto 2.  Desarrolle una calculadora científica que permita realizar las siguientes operaciones:

•	Operaciones aritméticas básicas: las operaciones aritméticas básicas son suma, resta, multiplicación, división.

•	Operaciones aritméticas extendidas: son la división entera, el residuo, la exponenciación a la n de número, raíz n (n puede ser 2, 3, 4, 5) de un número, logaritmo en base 10, logaritmo, valor absoluto, 1/número, factorial.

•	Operaciones trigonométricas: al menos dos, por ejemplo, seno(x), tangente(x).

•	Operaciones estadísticas básicas: promedio, media, mediana, moda.
"""

#RETO 4
#Estudiantes:

#Nombre 1: Ana María Patiño Cano
#Cédula 1: 1214724501
#Correo 1:  anampcano@gmail.com

#Nombre 2:  Andrés Danilo Arismendy Montoya
#Cédula 2: 1044101241
#Correo 2: darismon@hotmail.com


#DESARROLLO:

#Se definen primero las funciones para las operaciones aritméticas básicas:

def suma (a,b):
    return a + b

def resta (a,b):
    return a - b

def multiplicacion (a,b):
    return a * b

def division (a,b):
    if b == 0: #No es posible dividir por cero, entonces:
      return "No es posible hacer la operación"
    return round ((a / b), 2) #Agregamos round para ajustar cantidad de decimales

#Se definen primero las funciones para las operaciones aritméticas extendidas:

def division_entera (a,b):
    if b == 0:  #No es posible dividir por cero, entonces:
      return "No es posible hacer la operación"
    return a // b

def residuo (a,b):
    return a % b

def potenciacion (a,n): #Se pone n porque sería el exponente
    return a ** n

def radicacion_n (indice, radicando):  #Se pone n porque sería raíz n de un número
    if indice == 0:  #No es posible sacar raíz de cero, entonces:
      return "No es posible realizar la operación"
    return round (radicando ** (1/ indice), 2)

import math #Se importa la libería math para que las funciones "math.log()", "math.log10()", "math.sin"
from statistics import mean, median, mode #Se importa el módulo statistics para mean (promedio), median (mediana), mode (moda)

def logaritmacion(a,base):
    if a <= 0 or base <= 0 or base == 1:
    #Se agrega este condicional porque el logaritmo es válido para números mayores que cero únicamente
    #La base debe ser mayor que cero y diferente a 1
     return "No es posible realizar la operación"
    return round (math.log(a, base), 2) #Agregamos round para ajustar cantidad de decimales

def logaritmacion_base10(a):
    return round (math.log10(a), 2) #Agregamos round para ajustar cantidad de decimales

def valor_absoluto(a):
    return abs(a)

def inverso(a):
    if a == 0:  #No es posible sacar el inverso de cero, entonces:
      return "No es posible realizar la operación"
    return round (1 / a, 2) #Agregamos round para ajustar cantidad de decimales

def factorial (a):
    if a < 0:   #No es posible calcular factorial de números negativos, entonces:
      return "No es posible realizar la operación"
    if a == 0:
      return 1 #El factorial de 0 se define como 1
    resultado = 1
    for i in range (1, a + 1): #Usamos este bucle que itera desde 1 hasta "n"
      resultado *= i #En cada iteración del ciclo, el valor "i" se multiplicaría
      #con el valor de "result"
    return resultado

#Se definen primero las funciones para las operaciones trigonométricas:

def seno(n1): #Esta función debe solicitar ángulo en grados para luego
#convertir a radianes y así calculará el seno.
    radianes_ang = math.radians(n1)
    return round (math.sin(radianes_ang), 2)

def tangente(n1): #Esta función debe solicitar ángulo en grados para luego
#convertir a radianes y así calculará la tangente.
    radianes_ang = math.radians(n1)
    return round (math.tan(radianes_ang), 2)

#Se definen primero las funciones para las operaciones estadísticas básicas:

def promedio(num):
    return mean(num)

def mediana(num):
    return median(num)

def moda(num):
  return mode(num)

#Es necesario hacer menú aparte para las operaciones estadísticas básicas ya que
#la idea es que el usuario digite el conjunto de números y esos mismos sirvan para
#cualquier operación que busque:

def est_basicas():
    while True:
      print("""Operaciones estadísticas básicas:
      1. Promedio
      2. Mediana
      3. Moda
      4. Salir""")

      opcion_estadistica = input("Seleccione la operación estadística que desea realizar")
      #Aquí la variable opción pasa a llamarse "opcion_estadistica" para que no cree conflicto con variable local "opcion" en "menu_calculadora"
      if opcion_estadistica == "4":
        break

      n = int(input("Indique la cantidad de números total que ingresará: "))
      num = []  #Aquí se crea una lista vacía que almacenará los números del usuario

      for i in range(n): #Se crea bucle para ejecutarse n veces donde n es la cantidad
      #de números ingresados por el usuario
        numero = float(input(f"Ingrese el número {i + 1}: "))
        num.append(numero)

      if opcion_estadistica == "1":
        resultado = promedio(num)
        print (f"El promedio de los números ingresados es: {resultado}")

      if opcion_estadistica == "2":
        resultado = mediana(num)
        print(f"La mediana de los números ingresados es: {resultado}")

      if opcion_estadistica == "3":
        resultado = moda(num)
        print(f"La moda de los números ingresados es: {resultado}")

#Se despliega menú para que el usuario pueda elegir el tipo de operación que
#quiere realizar, usando ciclo para que se repita una vez termine.

def menu_calculadora():
    while True:
        print("""Bienvenido a la calculadora, estas son las operaciones que podemos desarrollar:

              Aritméticas básicas:
              1. Suma
              2. Resta
              3. Multiplicación
              4. División

              Aritméticas extendidas:
              5. División Entera
              6. Residuo
              7. Potenciación
              8. Radicación
              9. Logaritmación
              10. Logaritmación en base 10
              11. Valor Absoluto
              12. Inverso
              13. Factorial

              Trigonométricas:
              14. Seno
              15. Tangente

              16. Estadísticas básicas

              Otras opciones:
              17. Salir""")
        opcion = input("Indica la opción: ")

#Se aplica condicional para romper el ciclo si la opción elegida es "salir"
        if opcion == "17":
          break

        if opcion == "16":
            est_basicas()  # Llama a la función de operaciones estadísticas básicas
            continue

#A continuación, se establecen las entradas del usuario para indicar los números
#A los cuales les quiere realizar la operación elegida previamente
#Pero se establecen condicionales porque no todas las operaciones necesitan input de dos números:

        if opcion in ("1", "2", "3", "4", "5", "6", "7"):
            n1 = float(input("Introduce el primer número: "))
        if opcion in ("1", "2", "3", "4"):
            n2 = float(input("Introduce el segundo número: "))

        if opcion == "1":
          print ("El resultado de la suma es:", suma (n1,n2))
        elif opcion == "2":
          print ("El resultado de la resta es:", resta (n1,n2))
        elif opcion == "3":
          print ("El resultado de la multiplicación es:", multiplicacion (n1,n2))
        elif opcion == "4":
         print ("El resultado de la división es:", division (n1,n2))
        elif opcion == "5":
         print ("El resultado de la división entera es:", division_entera (n1,n2))
        elif opcion == "6":
         print ("El residuo es:", (n1,n2))
        elif opcion == "7":
          n2 = float(input("Introduce el exponente: "))
          print ("La potenciación es:", potenciacion (n1,n2))
        elif opcion == "8":
          n1 = float(input("Introduce el índice (n): "))
          n2 = float(input("Introduce el radicando: "))
          print("La raíz es:", radicacion_n (n1, n2))
        elif opcion == "9":
          n1 = float(input("Introduce el número: "))
          n2 = float(input("Introduce la base: "))
          resultado = logaritmacion(n1,n2)
          print(f"El logaritmo de {n1} en base {n2} es: {resultado}")
        elif opcion == "10":
          n1 = float(input("Ingrese el número: "))
          resultado = logaritmacion_base10(n1)
          print(f"El logaritmo base 10 de {n1} es: {resultado}")
        elif opcion == "11":
          n1 = float(input("Ingrese el número: "))
          resultado = valor_absoluto(n1)
          print(f"El valor absoluto de {n1} es: {resultado}")
        elif opcion == "12":
          n1 = float(input("Ingrese el número: "))
          resultado = inverso(n1)
          print(f"El inverso de {n1} es: {resultado}")
        elif opcion == "13":
          n1 = int(input("Ingrese el número: "))
          resultado = factorial(n1)
          print(f"El factorial de {n1} es: {resultado}")
        elif opcion == "14":
          n1 = int(input("Ingrese el ángulo en grados: "))
          resultado = seno(n1)
          print(f"El seno de {n1} es: {resultado}")
        elif opcion == "15":
          n1 = int(input("Ingrese el ángulo en grados: "))
          resultado = tangente(n1)
          print(f"La tangente de {n1} es: {resultado}")

        else:
          print("Opción no válida")

#Se llama la función para la calculadora
menu_calculadora()